### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by lesleychou** [shinshiner/Pytorch-pensieve#1]
Hi shinshiner,

Many thanks for your work of Pensieve with Pytorch.

I followed the README to go through the code. I got the Synthetic data, but when I was running your train/main.py, I got some error like below:
`Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lesley/Pytorch-pensieve/train/test.py", line 34, in test
    random_seed=50
  File "/home/lesley/Pytorch-pensieve/train/env.py", line 33, in __init__
    self.trace_idx = np.random.randint(len(self.all_cooked_time))
  File "mtrand.pyx", line 630, in numpy.random.mtrand.RandomState.randint
  File "bounded_integers.pyx", line 1228, in numpy.random.bounded_integers._rand_int64
ValueError: low >= high
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/lesley/Pytorch-pensieve/train/train.py", line 28, in train
    random_seed=rank
  File "/home/lesley/Pytorch-pensieve/train/env.py", line 33, in __init__
    self.trace_idx = np.random.randint(len(self.all_cooked_time))
  File "mtrand.pyx", line 630, in numpy.random.mtrand.RandomState.randint
  File "bounded_integers.pyx", line 1228, in numpy.random.bounded_integers._rand_int64
ValueError: low >= high`

Is this because the `self.all_cooked_time` is empty? 
For training, should I run some other file before running the main.py?

Looking forward to your reply!

**Comment by shinshiner** [comment]
Yes. You may generate some training or testing traces and specify the corresponding path in `main.py`, otherwise the default values are empty lists.

**Comment by lesleychou** [comment]
> Yes. You may generate some training or testing traces and specify the corresponding path in `main.py`, otherwise the default values are empty lists.

Yes, thanks very much! I just solved my stupid error:) it's training now!
